version: '3'
services:
  web:
    build:
      context: ../..
      dockerfile: ./environment/dev/Dockerfile
    image: dev/panic-fab
    container_name: panic-fab
    volumes:
      - ../..:/code
    ports:
      - "8080:8080"